# Generated by Django 3.0.4 on 2020-06-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(default='11111111111', max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default='123456', max_length=128)),
                ('identity', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Hr_message',
                'verbose_name_plural': 'Hr_message',
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(default='11111111111', max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default='123456', max_length=128)),
                ('identity', models.IntegerField(default=1)),
                ('free1', models.DateTimeField(blank=True, null=True)),
                ('free2', models.DateTimeField(blank=True, null=True)),
                ('free3', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'interviewer_message',
                'verbose_name_plural': 'interviewer_message',
            },
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(default='11111111111', max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default='123456', max_length=128)),
                ('identity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Superadmin_message',
                'verbose_name_plural': 'Superadmin_message',
            },
        ),
        migrations.CreateModel(
            name='superToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Super')),
            ],
            options={
                'verbose_name': 'Super_token',
                'verbose_name_plural': 'Super_token',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('exam', models.CharField(max_length=128)),
                ('tempeval', models.CharField(max_length=20)),
                ('finaleval', models.CharField(max_length=20)),
                ('accept', models.IntegerField()),
                ('record', models.CharField(max_length=128)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Interviewer')),
            ],
            options={
                'verbose_name': 'metting_room_message',
                'verbose_name_plural': 'metting_room_message',
            },
        ),
        migrations.CreateModel(
            name='interToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Interviewer')),
            ],
            options={
                'verbose_name': 'Interviewer_token',
                'verbose_name_plural': 'Interviewer_token',
            },
        ),
        migrations.CreateModel(
            name='hrToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Hr')),
            ],
            options={
                'verbose_name': 'Hr_token',
                'verbose_name_plural': 'Hr_token',
            },
        ),
    ]
