# Generated by Django 3.0.4 on 2020-05-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField()),
                ('image', models.ImageField(default='image/default.jpg', upload_to='image/%Y%m')),
            ],
            options={
                'verbose_name': 'applicant_message',
                'verbose_name_plural': 'applicant_message',
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('free1', models.DateTimeField(blank=True, null=True)),
                ('free2', models.DateTimeField(blank=True, null=True)),
                ('free3', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'interviewer_message',
                'verbose_name_plural': 'interviewer_message',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('exam', models.CharField(max_length=128)),
                ('tempeval', models.CharField(max_length=20)),
                ('finaleval', models.CharField(max_length=20)),
                ('accept', models.IntegerField()),
                ('record', models.CharField(max_length=128)),
                ('applyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Applicant')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Interviewer')),
            ],
            options={
                'verbose_name': 'metting_room_message',
                'verbose_name_plural': 'metting_room_message',
            },
        ),
    ]
