# Generated by Django 3.1 on 2020-08-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200811_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='finaleval',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='interviewee',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tempeval',
        ),
        migrations.AddField(
            model_name='interviewee',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
